name: Deploy static website to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A2CCE43F1B614677B0EE50EAEF2B335B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_51D8EB3742D9457BA3534D0F78C4780E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE837245AF3041A3A4FA0C9D12BB6C0F }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: dhrutiportfolio-26
          slot-name: Production
          package: .
